spring:
   kafka:
     consumer:
        #bootstrap-servers: kafka:9092
        bootstrap-servers: localhost:9092
        group-id: group_id
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8082

pulsar-config:
  serviceUrl: pulsar://localhost:6650